name: "[QAS] branch reset or rebase"
run-name: ${{ inputs.kind_action }} ${{ inputs.environment_choice }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_choice:
        description: "Select target branch"
        required: true
        type: choice
        options:
          - env/qas
          - env/qas2
          - env/qas3
          - env/qas4
          - env/qas5
          - env/qas5fix
          - env/qas6
      kind_action:
        description: "Select branch option"
        required: true
        type: choice
        options:
          - rebase
          - reset
jobs:
  rebase-branch:
    runs-on: ubuntu-latest
    if: ${{ inputs.kind_action == 'rebase' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_MS_CHALLANGE }}
      - name: rebase branch based on main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout ${{ inputs.environment_choice }}
          git rebase origin/main ${{ inputs.environment_choice }}
          git push --force
  reset-branch:
    runs-on: ubuntu-latest
    if: ${{ inputs.kind_action == 'reset' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_MS_CHALLANGE }}
      - name: reseting branch based on main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout ${{ inputs.environment_choice }}
          git reset --hard origin/main
          git push --force